import { ImageEntry } from './types';

// PLACEHOLDER CATALOG — update paths as real images are added to /public/images/
// Each entry maps to a file in /public/images/<category>/<filename>
// Tags are used for keyword matching against the child's question

export const IMAGE_LIBRARY: ImageEntry[] = [
  { path: '/images/animals/butterfly-01.webp', category: 'animals', tags: ['butterfly', 'insect', 'flying', 'colorful', 'wings'] },
  { path: '/images/animals/dog-01.webp', category: 'animals', tags: ['dog', 'puppy', 'pet', 'playing', 'bark'] },
  { path: '/images/animals/cat-01.webp', category: 'animals', tags: ['cat', 'kitten', 'pet', 'curious', 'purr'] },
  { path: '/images/animals/bird-01.webp', category: 'animals', tags: ['bird', 'flying', 'nest', 'singing', 'feather'] },
  { path: '/images/animals/fish-01.webp', category: 'animals', tags: ['fish', 'swimming', 'water', 'colorful', 'scales'] },
  { path: '/images/animals/dinosaur-01.webp', category: 'animals', tags: ['dinosaur', 'big', 'ancient', 'roar'] },
  { path: '/images/animals/rabbit-01.webp', category: 'animals', tags: ['rabbit', 'bunny', 'hopping', 'fluffy', 'carrot'] },
  { path: '/images/animals/elephant-01.webp', category: 'animals', tags: ['elephant', 'big', 'trunk', 'water', 'gray'] },
  { path: '/images/animals/frog-01.webp', category: 'animals', tags: ['frog', 'jumping', 'pond', 'green', 'ribbit'] },
  { path: '/images/animals/ant-01.webp', category: 'animals', tags: ['ant', 'insect', 'tiny', 'working', 'strong'] },
  { path: '/images/animals/bee-01.webp', category: 'animals', tags: ['bee', 'insect', 'honey', 'flower', 'buzzing'] },
  { path: '/images/animals/penguin-01.webp', category: 'animals', tags: ['penguin', 'ice', 'cold', 'waddle', 'snow'] },
  { path: '/images/animals/lion-01.webp', category: 'animals', tags: ['lion', 'jungle', 'roar', 'mane', 'brave'] },
  { path: '/images/animals/monkey-01.webp', category: 'animals', tags: ['monkey', 'climbing', 'tree', 'playful', 'banana'] },
  { path: '/images/animals/butterfly-02.webp', category: 'animals', tags: ['butterfly', 'garden', 'flowers', 'spring'] },

  { path: '/images/space/moon-01.webp', category: 'space', tags: ['moon', 'night', 'glowing', 'crater', 'round'] },
  { path: '/images/space/moon-02.webp', category: 'space', tags: ['moon', 'astronaut', 'footprint', 'surface'] },
  { path: '/images/space/stars-01.webp', category: 'space', tags: ['stars', 'night', 'twinkling', 'sky', 'shooting'] },
  { path: '/images/space/stars-02.webp', category: 'space', tags: ['stars', 'constellation', 'pattern', 'connect'] },
  { path: '/images/space/sun-01.webp', category: 'space', tags: ['sun', 'bright', 'warm', 'morning', 'rise'] },
  { path: '/images/space/planets-01.webp', category: 'space', tags: ['planets', 'solar system', 'saturn', 'rings', 'mars'] },
  { path: '/images/space/planets-02.webp', category: 'space', tags: ['planets', 'hopping', 'colorful', 'stepping'] },
  { path: '/images/space/rocket-01.webp', category: 'space', tags: ['rocket', 'launch', 'astronaut', 'flying', 'blast'] },
  { path: '/images/space/astronaut-01.webp', category: 'space', tags: ['astronaut', 'floating', 'space station', 'weightless'] },
  { path: '/images/space/milky-way-01.webp', category: 'space', tags: ['galaxy', 'milky way', 'stars', 'purple'] },
  { path: '/images/space/telescope-01.webp', category: 'space', tags: ['telescope', 'looking', 'rooftop', 'discover'] },
  { path: '/images/space/comet-01.webp', category: 'space', tags: ['comet', 'streak', 'bright', 'tail'] },
  { path: '/images/space/eclipse-01.webp', category: 'space', tags: ['eclipse', 'sun', 'moon', 'glasses'] },
  { path: '/images/space/night-sky-01.webp', category: 'space', tags: ['night', 'tent', 'camping', 'stars'] },
  { path: '/images/space/earth-01.webp', category: 'space', tags: ['earth', 'blue', 'planet', 'home', 'globe'] },

  { path: '/images/nature/tree-01.webp', category: 'nature', tags: ['tree', 'hugging', 'old', 'leaves', 'bark'] },
  { path: '/images/nature/flower-01.webp', category: 'nature', tags: ['flower', 'smelling', 'petals', 'garden', 'bloom'] },
  { path: '/images/nature/mountain-01.webp', category: 'nature', tags: ['mountain', 'top', 'climbing', 'clouds', 'high'] },
  { path: '/images/nature/river-01.webp', category: 'nature', tags: ['river', 'water', 'flowing', 'stones', 'toes'] },
  { path: '/images/nature/forest-01.webp', category: 'nature', tags: ['forest', 'trees', 'sunbeam', 'mushroom', 'path'] },
  { path: '/images/nature/leaf-01.webp', category: 'nature', tags: ['leaf', 'autumn', 'fall', 'colorful', 'holding'] },
  { path: '/images/nature/garden-01.webp', category: 'nature', tags: ['garden', 'planting', 'seed', 'sprout', 'growing'] },
  { path: '/images/nature/rainbow-01.webp', category: 'nature', tags: ['rainbow', 'rain', 'colors', 'field', 'arch'] },
  { path: '/images/nature/volcano-01.webp', category: 'nature', tags: ['volcano', 'lava', 'smoke', 'eruption', 'hot'] },
  { path: '/images/nature/waterfall-01.webp', category: 'nature', tags: ['waterfall', 'mist', 'splash', 'cliff'] },
  { path: '/images/nature/desert-01.webp', category: 'nature', tags: ['desert', 'sand', 'camel', 'cactus', 'dry'] },
  { path: '/images/nature/cave-01.webp', category: 'nature', tags: ['cave', 'crystal', 'lantern', 'glowing', 'explore'] },
  { path: '/images/nature/seed-01.webp', category: 'nature', tags: ['seed', 'growing', 'roots', 'sprout', 'underground'] },
  { path: '/images/nature/rain-forest-01.webp', category: 'nature', tags: ['rainforest', 'tropical', 'parrot', 'leaves', 'wet'] },
  { path: '/images/nature/meadow-01.webp', category: 'nature', tags: ['meadow', 'wildflowers', 'running', 'dandelion', 'sunny'] },

  { path: '/images/body/teeth-01.webp', category: 'body', tags: ['teeth', 'brushing', 'smile', 'toothbrush'] },
  { path: '/images/body/eyes-01.webp', category: 'body', tags: ['eyes', 'seeing', 'curious', 'looking', 'vision'] },
  { path: '/images/body/bones-01.webp', category: 'body', tags: ['bones', 'skeleton', 'inside', 'strong'] },
  { path: '/images/body/heart-01.webp', category: 'body', tags: ['heart', 'beating', 'stethoscope', 'pump', 'love'] },
  { path: '/images/body/brain-01.webp', category: 'body', tags: ['brain', 'thinking', 'ideas', 'smart', 'lightbulb'] },
  { path: '/images/body/stomach-01.webp', category: 'body', tags: ['stomach', 'tummy', 'eating', 'digest', 'food'] },
  { path: '/images/body/muscles-01.webp', category: 'body', tags: ['muscles', 'strong', 'flexing', 'arm', 'exercise'] },
  { path: '/images/body/sleep-01.webp', category: 'body', tags: ['sleep', 'dreaming', 'bed', 'night', 'rest'] },
  { path: '/images/body/sneeze-01.webp', category: 'body', tags: ['sneeze', 'nose', 'achoo', 'germs', 'funny'] },
  { path: '/images/body/tears-01.webp', category: 'body', tags: ['tears', 'crying', 'eyes', 'water', 'bandage'] },
  { path: '/images/body/hair-01.webp', category: 'body', tags: ['hair', 'growing', 'curly', 'straight', 'funny'] },
  { path: '/images/body/ears-01.webp', category: 'body', tags: ['ears', 'hearing', 'listening', 'sound', 'music'] },
  { path: '/images/body/breathing-01.webp', category: 'body', tags: ['breathing', 'lungs', 'air', 'calm', 'yoga'] },
  { path: '/images/body/growing-01.webp', category: 'body', tags: ['growing', 'height', 'tall', 'measuring', 'bigger'] },
  { path: '/images/body/fingerprint-01.webp', category: 'body', tags: ['fingerprint', 'unique', 'pattern', 'magnifying'] },

  { path: '/images/food/fruit-01.webp', category: 'food', tags: ['fruit', 'apple', 'orange', 'mango', 'picking'] },
  { path: '/images/food/icecream-01.webp', category: 'food', tags: ['ice cream', 'cone', 'scoops', 'sprinkles', 'cold'] },
  { path: '/images/food/cooking-01.webp', category: 'food', tags: ['cooking', 'kitchen', 'pot', 'stirring', 'steam'] },
  { path: '/images/food/milk-01.webp', category: 'food', tags: ['milk', 'cow', 'glass', 'white', 'pouring'] },
  { path: '/images/food/bread-01.webp', category: 'food', tags: ['bread', 'baking', 'dough', 'oven', 'flour'] },
  { path: '/images/food/vegetables-01.webp', category: 'food', tags: ['vegetables', 'carrot', 'tomato', 'garden', 'healthy'] },
  { path: '/images/food/chocolate-01.webp', category: 'food', tags: ['chocolate', 'candy', 'sweet', 'river', 'factory'] },
  { path: '/images/food/rice-01.webp', category: 'food', tags: ['rice', 'dal', 'indian food', 'plate', 'eating'] },
  { path: '/images/food/honey-01.webp', category: 'food', tags: ['honey', 'bee', 'jar', 'golden', 'sweet'] },
  { path: '/images/food/water-01.webp', category: 'food', tags: ['water', 'drinking', 'glass', 'thirst', 'clean'] },
  { path: '/images/food/mango-01.webp', category: 'food', tags: ['mango', 'summer', 'yellow', 'tree', 'juicy'] },
  { path: '/images/food/egg-01.webp', category: 'food', tags: ['egg', 'chick', 'hatching', 'shell', 'nest'] },
  { path: '/images/food/pizza-01.webp', category: 'food', tags: ['pizza', 'cheese', 'toppings', 'round', 'yummy'] },
  { path: '/images/food/seeds-01.webp', category: 'food', tags: ['seeds', 'planting', 'growing', 'sprout', 'garden'] },
  { path: '/images/food/spice-01.webp', category: 'food', tags: ['spice', 'turmeric', 'chili', 'colorful', 'powder'] },

  { path: '/images/weather/rain-01.webp', category: 'weather', tags: ['rain', 'puddle', 'splash', 'raincoat', 'umbrella'] },
  { path: '/images/weather/rainbow-01.webp', category: 'weather', tags: ['rainbow', 'sliding', 'colors', 'sky', 'after rain'] },
  { path: '/images/weather/snow-01.webp', category: 'weather', tags: ['snow', 'snowflake', 'cold', 'winter', 'catching'] },
  { path: '/images/weather/thunder-01.webp', category: 'weather', tags: ['thunder', 'lightning', 'storm', 'window', 'blanket'] },
  { path: '/images/weather/wind-01.webp', category: 'weather', tags: ['wind', 'kite', 'blowing', 'leaves', 'hair'] },
  { path: '/images/weather/cloud-01.webp', category: 'weather', tags: ['cloud', 'shapes', 'fluffy', 'sky', 'watching'] },
  { path: '/images/weather/fog-01.webp', category: 'weather', tags: ['fog', 'mist', 'morning', 'mysterious', 'white'] },
  { path: '/images/weather/hot-01.webp', category: 'weather', tags: ['hot', 'summer', 'sun', 'fan', 'lemonade'] },
  { path: '/images/weather/cold-01.webp', category: 'weather', tags: ['cold', 'frost', 'breath', 'scarf', 'winter'] },
  { path: '/images/weather/storm-01.webp', category: 'weather', tags: ['storm', 'treehouse', 'rain', 'cozy', 'safe'] },
  { path: '/images/weather/seasons-01.webp', category: 'weather', tags: ['seasons', 'spring', 'summer', 'autumn', 'winter'] },
  { path: '/images/weather/sunrise-01.webp', category: 'weather', tags: ['sunrise', 'morning', 'golden', 'dawn', 'hill'] },
  { path: '/images/weather/sunset-01.webp', category: 'weather', tags: ['sunset', 'evening', 'orange', 'pink', 'lake'] },
  { path: '/images/weather/hail-01.webp', category: 'weather', tags: ['hail', 'ice', 'balls', 'palm', 'marble'] },
  { path: '/images/weather/dew-01.webp', category: 'weather', tags: ['dew', 'drops', 'morning', 'spider web', 'sparkle'] },

  { path: '/images/ocean/underwater-01.webp', category: 'ocean', tags: ['underwater', 'diving', 'fish', 'coral', 'swimming'] },
  { path: '/images/ocean/whale-01.webp', category: 'ocean', tags: ['whale', 'big', 'blue', 'boat', 'spraying'] },
  { path: '/images/ocean/shell-01.webp', category: 'ocean', tags: ['shell', 'beach', 'listening', 'ocean sound', 'spiral'] },
  { path: '/images/ocean/wave-01.webp', category: 'ocean', tags: ['wave', 'beach', 'feet', 'splash', 'sand'] },
  { path: '/images/ocean/coral-01.webp', category: 'ocean', tags: ['coral', 'reef', 'colorful', 'fish', 'glass bottom'] },
  { path: '/images/ocean/dolphin-01.webp', category: 'ocean', tags: ['dolphin', 'jumping', 'riding', 'friendly', 'splash'] },
  { path: '/images/ocean/starfish-01.webp', category: 'ocean', tags: ['starfish', 'tide pool', 'orange', 'five arms'] },
  { path: '/images/ocean/jellyfish-01.webp', category: 'ocean', tags: ['jellyfish', 'glowing', 'floating', 'deep', 'purple'] },
  { path: '/images/ocean/octopus-01.webp', category: 'ocean', tags: ['octopus', 'tentacles', 'purple', 'friendly', 'wave'] },
  { path: '/images/ocean/sand-castle-01.webp', category: 'ocean', tags: ['sand castle', 'beach', 'building', 'moat', 'flag'] },
  { path: '/images/ocean/lighthouse-01.webp', category: 'ocean', tags: ['lighthouse', 'cliff', 'beam', 'light', 'night'] },
  { path: '/images/ocean/pirate-01.webp', category: 'ocean', tags: ['pirate', 'treasure', 'map', 'boat', 'parrot'] },
  { path: '/images/ocean/seaweed-01.webp', category: 'ocean', tags: ['seaweed', 'underwater', 'forest', 'green', 'fish'] },
  { path: '/images/ocean/crab-01.webp', category: 'ocean', tags: ['crab', 'sideways', 'red', 'beach', 'rocky'] },
  { path: '/images/ocean/island-01.webp', category: 'ocean', tags: ['island', 'palm tree', 'tropical', 'treasure', 'blue water'] },

  { path: '/images/transport/rocket-01.webp', category: 'transport', tags: ['rocket', 'cockpit', 'buttons', 'space', 'flying'] },
  { path: '/images/transport/train-01.webp', category: 'transport', tags: ['train', 'steam', 'tracks', 'waving', 'hills'] },
  { path: '/images/transport/airplane-01.webp', category: 'transport', tags: ['airplane', 'window', 'clouds', 'flying', 'sky'] },
  { path: '/images/transport/bicycle-01.webp', category: 'transport', tags: ['bicycle', 'riding', 'path', 'basket', 'flowers'] },
  { path: '/images/transport/boat-01.webp', category: 'transport', tags: ['boat', 'rowing', 'lake', 'duck', 'calm'] },
  { path: '/images/transport/bus-01.webp', category: 'transport', tags: ['bus', 'school', 'yellow', 'riding', 'friends'] },
  { path: '/images/transport/car-01.webp', category: 'transport', tags: ['car', 'driving', 'toy', 'steering', 'road'] },
  { path: '/images/transport/submarine-01.webp', category: 'transport', tags: ['submarine', 'yellow', 'underwater', 'porthole', 'deep'] },
  { path: '/images/transport/hot-air-balloon-01.webp', category: 'transport', tags: ['balloon', 'hot air', 'flying', 'colorful', 'floating'] },
  { path: '/images/transport/helicopter-01.webp', category: 'transport', tags: ['helicopter', 'propeller', 'flying', 'goggles', 'pilot'] },
  { path: '/images/transport/scooter-01.webp', category: 'transport', tags: ['scooter', 'kick', 'sidewalk', 'riding', 'fast'] },
  { path: '/images/transport/fire-truck-01.webp', category: 'transport', tags: ['fire truck', 'red', 'siren', 'firefighter', 'hose'] },
  { path: '/images/transport/spaceship-01.webp', category: 'transport', tags: ['spaceship', 'floating', 'corridor', 'zero gravity'] },
  { path: '/images/transport/wheel-01.webp', category: 'transport', tags: ['wheel', 'invention', 'round', 'rolling', 'history'] },
  { path: '/images/transport/magic-carpet-01.webp', category: 'transport', tags: ['magic carpet', 'flying', 'city', 'sunset', 'indian'] },

  { path: '/images/colors/rainbow-paint-01.webp', category: 'colors', tags: ['painting', 'colors', 'rainbow', 'brush', 'splash'] },
  { path: '/images/colors/prism-01.webp', category: 'colors', tags: ['prism', 'light', 'rainbow', 'glass', 'sunbeam'] },
  { path: '/images/colors/music-01.webp', category: 'colors', tags: ['music', 'piano', 'notes', 'playing', 'melody'] },
  { path: '/images/colors/drum-01.webp', category: 'colors', tags: ['drum', 'tabla', 'rhythm', 'sound', 'beat'] },
  { path: '/images/colors/mixing-01.webp', category: 'colors', tags: ['mixing', 'paint', 'blue', 'yellow', 'green', 'red'] },
  { path: '/images/colors/shadow-01.webp', category: 'colors', tags: ['shadow', 'flashlight', 'puppets', 'wall', 'dark'] },
  { path: '/images/colors/singing-01.webp', category: 'colors', tags: ['singing', 'voice', 'notes', 'loud', 'mouth'] },
  { path: '/images/colors/fireworks-01.webp', category: 'colors', tags: ['fireworks', 'diwali', 'sparkler', 'night', 'celebration'] },
  { path: '/images/colors/glow-01.webp', category: 'colors', tags: ['glow', 'fireflies', 'jar', 'night', 'green light'] },
  { path: '/images/colors/echo-01.webp', category: 'colors', tags: ['echo', 'mountain', 'shouting', 'canyon', 'sound'] },

  { path: '/images/wonder/curious-01.webp', category: 'wonder', tags: ['curious', 'magnifying glass', 'exploring', 'backyard'] },
  { path: '/images/wonder/question-01.webp', category: 'wonder', tags: ['question', 'thinking', 'wondering', 'question marks'] },
  { path: '/images/wonder/book-01.webp', category: 'wonder', tags: ['book', 'reading', 'magic', 'glowing', 'story'] },
  { path: '/images/wonder/telescope-01.webp', category: 'wonder', tags: ['telescope', 'cardboard', 'looking', 'imagination'] },
  { path: '/images/wonder/adventure-01.webp', category: 'wonder', tags: ['adventure', 'door', 'magical', 'unknown', 'backpack'] },
  { path: '/images/wonder/discovery-01.webp', category: 'wonder', tags: ['discovery', 'treasure', 'chest', 'golden light'] },
  { path: '/images/wonder/thinking-01.webp', category: 'wonder', tags: ['thinking', 'lying', 'grass', 'sky', 'daydream'] },
  { path: '/images/wonder/experiment-01.webp', category: 'wonder', tags: ['experiment', 'science', 'mixing', 'fizz', 'bubbles'] },
  { path: '/images/wonder/map-01.webp', category: 'wonder', tags: ['map', 'treasure', 'following', 'dotted line'] },
  { path: '/images/wonder/dream-01.webp', category: 'wonder', tags: ['dream', 'sleeping', 'floating', 'moon', 'clouds'] },
  { path: '/images/wonder/library-01.webp', category: 'wonder', tags: ['library', 'books', 'flying', 'magical', 'fairy dust'] },
  { path: '/images/wonder/lamp-01.webp', category: 'wonder', tags: ['lamp', 'genie', 'magic', 'wish', 'sparkle'] },
  { path: '/images/wonder/friends-01.webp', category: 'wonder', tags: ['friends', 'animals', 'picnic', 'circle', 'nature'] },
  { path: '/images/wonder/night-walk-01.webp', category: 'wonder', tags: ['night', 'walk', 'moonlit', 'fireflies', 'owl'] },
  { path: '/images/wonder/birthday-01.webp', category: 'wonder', tags: ['birthday', 'cake', 'candles', 'celebration', 'party'] },
];
